### ISSUE TITLE
Wrong index gets updated

### ISSUE THREAD

**Issue by sjelfull** [ezekielaquino/Cactus#6]
![image](https://user-images.githubusercontent.com/10508/56571138-9c2d9200-65bc-11e9-80ff-2269313737e4.png)

1. Wrote some stuff
2. Added a new row
3. Reordered it

Now it updates and deleted the wrong index.

**Comment by rensverschuren** [comment]
Fixed, probably in conjunction with 16df4ab58b158b467c02cd2aee316b26eb226d96
